
def get_columns():
    return [
        # "faceAttributes.age",
        #"faceAttributes.emotion.anger",
        "faceAttributes.emotion.contempt",
        #"faceAttributes.emotion.disgust",
        #"faceAttributes.emotion.fear",
        "faceAttributes.emotion.happiness",
        "faceAttributes.emotion.neutral",
        #"faceAttributes.emotion.sadness",
        #"faceAttributes.emotion.surprise",
        # "faceAttributes.facialHair.beard",
        # "faceAttributes.facialHair.moustache",
        # "faceAttributes.facialHair.sideburns",
        # "faceAttributes.gender",
        # "faceAttributes.glasses",
        # "faceAttributes.headPose.pitch",
        # "faceAttributes.headPose.roll",
        # "faceAttributes.headPose.yaw",
        # "faceAttributes.smile",
        # "faceLandmarks.eyeLeftBottom.x",
        # "faceLandmarks.eyeLeftBottom.y",
        # "faceLandmarks.eyeLeftInner.x",
        # "faceLandmarks.eyeLeftInner.y",
        # "faceLandmarks.eyeLeftOuter.x",
        # "faceLandmarks.eyeLeftOuter.y",
        # "faceLandmarks.eyeLeftTop.x",
        # "faceLandmarks.eyeLeftTop.y",
        # "faceLandmarks.eyeRightBottom.x",
        # "faceLandmarks.eyeRightBottom.y",
        # "faceLandmarks.eyeRightInner.x",
        # "faceLandmarks.eyeRightInner.y",
        # "faceLandmarks.eyeRightOuter.x",
        # "faceLandmarks.eyeRightOuter.y",
        # "faceLandmarks.eyeRightTop.x",
        # "faceLandmarks.eyeRightTop.y",
        # "faceLandmarks.eyebrowLeftInner.x",
        # "faceLandmarks.eyebrowLeftInner.y",
        # "faceLandmarks.eyebrowLeftOuter.x",
        # "faceLandmarks.eyebrowLeftOuter.y",
        # "faceLandmarks.eyebrowRightInner.x",
        # "faceLandmarks.eyebrowRightInner.y",
        # "faceLandmarks.eyebrowRightOuter.x",
        # "faceLandmarks.eyebrowRightOuter.y",
        # "faceLandmarks.mouthLeft.x",
        # "faceLandmarks.mouthLeft.y",
        # "faceLandmarks.mouthRight.x",
        # "faceLandmarks.mouthRight.y",
        # "faceLandmarks.noseLeftAlarOutTip.x",
        # "faceLandmarks.noseLeftAlarOutTip.y",
        # "faceLandmarks.noseLeftAlarTop.x",
        # "faceLandmarks.noseLeftAlarTop.y",
        # "faceLandmarks.noseRightAlarOutTip.x",
        # "faceLandmarks.noseRightAlarOutTip.y",
        # "faceLandmarks.noseRightAlarTop.x",
        # "faceLandmarks.noseRightAlarTop.y",
        # "faceLandmarks.noseRootLeft.x",
        # "faceLandmarks.noseRootLeft.y",
        # "faceLandmarks.noseRootRight.x",
        # "faceLandmarks.noseRootRight.y",
        # "faceLandmarks.noseTip.x",
        # "faceLandmarks.noseTip.y",
        # "faceLandmarks.pupilLeft.x",
        # "faceLandmarks.pupilLeft.y",
        # "faceLandmarks.pupilRight.x",
        # "faceLandmarks.pupilRight.y",
        # "faceLandmarks.underLipBottom.x",
        # "faceLandmarks.underLipBottom.y",
        # "faceLandmarks.underLipTop.x",
        # "faceLandmarks.underLipTop.y",
        # "faceLandmarks.upperLipBottom.x",
        # "faceLandmarks.upperLipBottom.y",
        # "faceLandmarks.upperLipTop.x",
        # "faceLandmarks.upperLipTop.y",
        # "img_id",
        # "img_url",
        # "country",
        # "salary"
         ]